import { existsSync, readFileSync, writeFileSync, appendFileSync } from "node:fs";
import { resolve } from "node:path";
import pc from "picocolors";

interface PackageJson {
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

type Framework = "next" | "vite" | "remix" | "node";

function detectFramework(pkg: PackageJson): Framework {
  const all = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
  if (all.next) return "next";
  if (all["@remix-run/node"] ?? all["@remix-run/react"]) return "remix";
  if (all.vite) return "vite";
  return "node";
}

function hasDevScript(pkg: PackageJson): boolean {
  const s = pkg.scripts ?? {};
  return typeof s.dev === "string" || typeof s.start === "string";
}

function defaultConfigSource(opts: { framework: Framework; smokeEnabled: boolean }): string {
  const baseUrl =
    opts.framework === "next" ? "http://localhost:3000" : "http://localhost:5173";
  return `import { defineConfig } from "agentqa";

// AgentQA — Auto-generated by \`agentqa init\`. Edit freely.
// Detected framework: ${opts.framework}
export default defineConfig({
  agents: {
    functional: { enabled: true, scope: ["src/**", "app/**"] },
    regression: { enabled: true, depth: "shallow" },
    smoke: {
      enabled: ${opts.smokeEnabled ? "true" : "false"},
      baseUrl: process.env.AGENTQA_PREVIEW_URL ?? "${baseUrl}",
      routes: ["/"],
    },
    custom: [],
  },
  reporters: ["json", "markdown", "github-pr-comment"],
  gate: { failOn: ["critical"] },
  budget: { maxTotalUsd: 0.5 },
});
`;
}

export interface InitOptions {
  cwd?: string;
  force?: boolean;
}

export interface InitResult {
  configPath: string;
  framework: Framework;
  smokeEnabled: boolean;
  alreadyExisted: boolean;
}

export function runInit(opts: InitOptions = {}): InitResult {
  const cwd = resolve(opts.cwd ?? process.cwd());
  const pkgPath = resolve(cwd, "package.json");
  if (!existsSync(pkgPath)) {
    throw new Error(
      `No package.json found at ${pkgPath}. Run \`agentqa init\` from the host project root.`,
    );
  }
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as PackageJson;
  const framework = detectFramework(pkg);
  const smokeEnabled = hasDevScript(pkg);

  const configPath = resolve(cwd, "agentqa.config.ts");
  const alreadyExisted = existsSync(configPath);
  if (alreadyExisted && !opts.force) {
    return { configPath, framework, smokeEnabled, alreadyExisted };
  }
  writeFileSync(configPath, defaultConfigSource({ framework, smokeEnabled }), "utf8");

  // Add .agentqa-cache/ to .gitignore (idempotent)
  const giPath = resolve(cwd, ".gitignore");
  const giEntry = ".agentqa-cache/";
  if (existsSync(giPath)) {
    const gi = readFileSync(giPath, "utf8");
    if (!gi.split(/\r?\n/).includes(giEntry)) {
      appendFileSync(giPath, `\n${giEntry}\n`, "utf8");
    }
  } else {
    writeFileSync(giPath, `${giEntry}\n`, "utf8");
  }

  return { configPath, framework, smokeEnabled, alreadyExisted: false };
}

export function printInitResult(r: InitResult): void {
  if (r.alreadyExisted) {
    console.log(
      pc.yellow(`agentqa.config.ts already exists at ${r.configPath} — use --force to overwrite.`),
    );
    return;
  }
  console.log(pc.green(`✓ Wrote ${r.configPath}`));
  console.log(`  detected framework: ${pc.bold(r.framework)}`);
  console.log(`  smoke runner: ${r.smokeEnabled ? pc.green("enabled") : pc.dim("disabled (no dev/start script)")}`);
  console.log("");
  console.log("Next:");
  console.log("  1. Add ANTHROPIC_API_KEY to your repo secrets");
  console.log("  2. Copy .github/workflows/agentqa.yml from the AgentQA README into your repo");
  console.log("  3. Open a PR — AgentQA will comment within ~90s");
}
